export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as AddressBook } from './AddressBook'
export { default as AddAddress } from './AddAddress'
export { default as AuthCard } from './AuthCard'
export { default as ChangePW } from './ChangePW'
export { default as DeleteAcc } from './DeleteAcc'
export { default as AboutUs } from './AboutUs'
export { default as Invitation } from './Invitation'
export { default as ComingSoon } from './ComingSoon'
export { default as Trade } from './Trade'
export { default as Records } from './Records'

/*export { default as Withdrawal } from './Withdrawal'
export { default as Deposit } from './Deposit'*/